Added Confirm buy/sell/try luck menu.
FD-Forks/Shop-Core pull request #114
Opened 2022-01-12 14:03 UTC by oylsister

2022-03-25 19:16 UTC, R1KO requested changes

2022-03-25 19:16 UTC, R1KO commented on addons/sourcemod/scripting/shop.sp
> +	menu.SetTitle("Are you sure that you going to purchase this item?");
translations?

2022-03-25 19:16 UTC, R1KO commented on addons/sourcemod/scripting/shop/functions.sp
> +	FormatEx(buffer, sizeof(buffer), "%t", "Yes");
`FormatEx(buffer, sizeof(buffer), "%T", "Yes", client);`

2022-03-25 19:16 UTC, R1KO commented on addons/sourcemod/scripting/shop/functions.sp
> +	FormatEx(buffer, sizeof(buffer), "%t\n", "confirm_luck", g_hLuckCredits.IntValue);
add space after `\n`

2022-03-25 19:16 UTC, R1KO commented on addons/sourcemod/scripting/shop/functions.sp
> +	menu.AddItem("b", buffer);
why `a` and `b` ?

2022-03-28 14:38 UTC, oylsister commented
I have closed this pull request due to reworking confirm menu has been done

2022-03-28 14:38 UTC, closed without merging