Added OnCredits* forwards
FD-Forks/Shop-Core pull request #82
Opened 2020-11-11 11:55 UTC by IL0co

Adding forwards:
Shop_OnCreditsSeted();
Shop_OnCreditsGivened();
Shop_OnCreditsTakened();

2020-11-11 12:34 UTC, RealFaya commented
https://github.com/FD-Forks/Shop-Core/blob/master/addons/sourcemod/scripting/include/shop.inc#L140
https://github.com/FD-Forks/Shop-Core/blob/master/addons/sourcemod/scripting/include/shop.inc#L151
https://github.com/FD-Forks/Shop-Core/blob/master/addons/sourcemod/scripting/include/shop.inc#L162

2020-11-11 12:49 UTC, R1KO commented
чет мне не очень нравлятся такие названия.
мб всё таки юзать постфикс `Post` ?

2020-11-11 17:59 UTC, TiBarification reviewed
I think we need to move _client-based_ forwards and natives to `players.inc` and rename related forwards and natives to appropriate values.

2020-11-11 19:34 UTC, R1KO requested changes

2020-11-11 19:34 UTC, R1KO commented on addons/sourcemod/scripting/shop/forwards.sp
> +Action Forward_OnCreditsSet_Post(int client, int &credits, int by_who)
почему credits по ссылке?

2020-11-11 19:34 UTC, R1KO commented on addons/sourcemod/scripting/include/shop.inc
> +forward void Shop_OnCreditsSet_Post(int client, int credits, int by_who);
согласен с тем, что все наверное все нативы и форварды связанные с кредитами и игроками стоит перенести в players.inc

2020-11-12 13:46 UTC, R1KO approved these changes

2020-11-12 20:14 UTC, TiBarification approved these changes

2020-11-15 20:48 UTC, merged